language: java
before_install:
- curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
- chmod a+x ~/bin/repo
- repo init -u https://github.com/manifest -b lollipop
- repo sync
- . build/envsetup.sh
- lunch aosp_mako-userdebug
script: mka otapackage
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
