language: java
before_install:
- mkdir ~/bin
- PATH=~/bin:$PATH
- sudo apt-get update
- sudo apt-get -f install git gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw32 tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386
- sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so
- curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
- chmod a+x ~/bin/repo
- git config --global user.email "shouvik.dey3993@gmail.com"
- git config --global user.name "sd3993"
- git config --global color.ui true
- mkdir l
- cd l
- repo init -u https://github.com/exdroid/manifest -b lollipop
- repo sync -q -j100
- . build/envsetup.sh
- lunch aosp_mako-userdebug
script: make otapackage -s -j10
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
