sudo: false
language: java
before_install:
- cd ~/
- ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
- cat ~/.ssh/id_rsa.pub
- sleep 15
- git config --global push.default simple
- git config --global user.email "shouvik.dey3993@gmail.com"
- git config --global user.name "sd3993"
- git clone https://android.googlesource.com/platform/packages/apps/Settings.git --branch android-5.1.1_r24
- cd Settings
- git remote add exdroid git@github.com:exdroid/packages_apps_Settings.git
- git checkout -b m6x
- git status
- git reset --hard
- git push -u -v exdroid
- cd ..
- git clone https://android.googlesource.com/platform/frameworks/base.git
- cd base
- git remote add exdroid git@github.com:exdroid/frameworks_base.git
- git checkout -b m6x
- git status
- git reset --hard
- git push -u -v exdroid
script:
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
