language: java
before_install:
- mkdir ~/bin
- PATH=~/bin:$PATH
- sudo apt-get install bison g++-multilib git gperf libxml2-utils
- curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
- chmod a+x ~/bin/repo
- git config --global user.email "shouvik.dey3993@gmail.com"
- git config --global user.name "sd3993"
- git config --global color.ui true
- mkdir l
- cd l
- repo init -u https://github.com/exdroid/manifest -b lollipop
- repo sync -q -j50
- . build/envsetup.sh
- lunch xd_mako-userdebug
script: make otapackage -s -j10
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
