language: java
before_install:
- cd ~/
- mkdir settings && cd settings
- git init
- git config --global credential.helper cache
- git config --global user.email "shouvik.dey3993@gmail.com"
- git config --global user.name "sd3993"
- git clone https://android.googlesource.com/platform/packages/apps/Settings.git lollipop-mr1-release
- git checkout -b m6x
- git remote add exdroid https://github.com/exdroid/packages_apps_Settings.git
- git push -u exdroid
script:
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
